# Generated by Django 2.0 on 2018-06-05 02:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('resume', models.FileField(blank=True, upload_to='uploads/')),
                ('about', tinymce.models.HTMLField()),
                ('links', django.contrib.postgres.fields.jsonb.JSONField()),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
